header:
  title: Header_name_here
  description: description_here # Needs to be here, but can be empty.
  url: url_here # If you don't wan't to add a custom URL, you can add "https://gwo.io".

fields:
  1:
    title: title_here
    description: description_here
  2:
    title: title_here
    description: description_here
  # There can be as many fields as you wish.

# Footer is optional.
footer: footer_here

# Color is optional.
color: 0xb02fbc
# show_thumbnail is also optional and if not given False!
show_thumbnail: False
